# This file is auto-generated by the code_generator (one-time action)
#
# Cookbook Name:: parted-hpc
# Spec:: default
#
# Copyright (c) 2016 The Authors, All Rights Reserved.

require 'spec_helper'

describe 'parted-hpc::default' do
end
